import 'package:isar/isar.dart';

part 'todo.g.dart'; // This will be generated by Isar

@collection
class Todo {
  Id id = Isar.autoIncrement; // Auto-incrementing ID for Isar

  late String title;
  bool isDone;

  Todo({required this.title, this.isDone = false});

  // Copy with method for immutability
  Todo copyWith({Id? id, String? title, bool? isDone}) {
    final todo = Todo(title: title ?? this.title, isDone: isDone ?? this.isDone);
    if (id != null) {
      todo.id = id;
    } else {
      todo.id = this.id; // Preserve existing id if not provided
    }
    return todo;
  }

  // Convert to Map for JSON serialization (optional, but good practice)
  Map<String, dynamic> toMap() {
    return {'id': id, 'title': title, 'isDone': isDone};
  }

  // Create Todo from Map (optional, but good practice)
  factory Todo.fromMap(Map<String, dynamic> map) {
    final todo = Todo(title: map['title'] ?? '', isDone: map['isDone'] ?? false);
    if (map['id'] != null) {
      todo.id = map['id'];
    }
    return todo;
  }

  @override
  /// Whether this [Todo] is equal to [other].
  ///
  /// Two todos are equal if and only if they have the same [id].
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is Todo && other.id == id;
  }

  @override
  int get hashCode => id.hashCode;
}
